// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBofH7Xo8gFlRN2uZkmrfuxLMNsYVwMo1g',
    appId: '1:957556808661:web:fb044de9f13f5f1617fb5c',
    messagingSenderId: '957556808661',
    projectId: 'servicly-app-c3984',
    authDomain: 'servicly-app-c3984.firebaseapp.com',
    storageBucket: 'servicly-app-c3984.firebasestorage.app',
    measurementId: 'G-H5V3WS00RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIr2aK9YgHgqY94Q3ik3uXwCKMeyvb-Wk',
    appId: '1:957556808661:android:56f8336db6c5b14017fb5c',
    messagingSenderId: '957556808661',
    projectId: 'servicly-app-c3984',
    storageBucket: 'servicly-app-c3984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL5b3u7mxbcK_FFpTWKnc1NC_YiwkmxkQ',
    appId: '1:957556808661:ios:dfa6949cf67a287217fb5c',
    messagingSenderId: '957556808661',
    projectId: 'servicly-app-c3984',
    storageBucket: 'servicly-app-c3984.firebasestorage.app',
    androidClientId: '957556808661-85onsn2n6k4o3cb8impc2cs46f4rb2pn.apps.googleusercontent.com',
    iosClientId: '957556808661-docoeijln9amrnj5655ctr9bne0oeetn.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviclyAppNueva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL5b3u7mxbcK_FFpTWKnc1NC_YiwkmxkQ',
    appId: '1:957556808661:ios:dfa6949cf67a287217fb5c',
    messagingSenderId: '957556808661',
    projectId: 'servicly-app-c3984',
    storageBucket: 'servicly-app-c3984.firebasestorage.app',
    androidClientId: '957556808661-85onsn2n6k4o3cb8impc2cs46f4rb2pn.apps.googleusercontent.com',
    iosClientId: '957556808661-docoeijln9amrnj5655ctr9bne0oeetn.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviclyAppNueva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBofH7Xo8gFlRN2uZkmrfuxLMNsYVwMo1g',
    appId: '1:957556808661:web:2c8f2945a6d972a917fb5c',
    messagingSenderId: '957556808661',
    projectId: 'servicly-app-c3984',
    authDomain: 'servicly-app-c3984.firebaseapp.com',
    storageBucket: 'servicly-app-c3984.firebasestorage.app',
    measurementId: 'G-8PSXKYD4R3',
  );

}