const List<String> kCategoriasDeServicios = [
  'Plomería',
  'Gasista',
  'Carpintería',
  'Pintor',
  'Albañil',
  'Electricista',
  'Refrigeración',
  'Arquitectura y construcción',
  'Técnicos',
  'Jardinería',
  'Seguridad',
  'Decorador',
  'Mudanzas y fletes',
  'Herrería',
  'Cerrajero',
  'Limpieza',
  'Control de plagas',
  'Soldador',
  'Mecanico',
  'Cuidados Mascotas',
  'Cuidados niños',
  'Cuidados adultos',
  'Otros',
];